import { useEffect, useState } from "react";
import { api } from "../api";

type SettingsData = { tenant_id: number; activation_fee_toman: number; settings: { currency?: string; support_username?: string; support_url?: string; referral_percent?: number }; branding: { logo_url?: string | null; primary_color?: string | null; display_name?: string | null } };
type PlatformData = { manual_payment: { activation_fee_toman: number; card_number: string; card_holder: string; bank: string } };

export default function Settings() {
  const [tenantId, setTenantId] = useState(localStorage.getItem("tenant_id") || "");
  const [data, setData] = useState<SettingsData | null>(null);
  const [platform, setPlatform] = useState<PlatformData | null>(null);
  const [currency, setCurrency] = useState("IRT"); const [supportUsername, setSupportUsername] = useState(""); const [supportUrl, setSupportUrl] = useState(""); const [referral, setReferral] = useState("0"); const [displayName, setDisplayName] = useState(""); const [primaryColor, setPrimaryColor] = useState("");
  const [fee, setFee] = useState("250000"); const [cardNumber, setCardNumber] = useState(""); const [cardHolder, setCardHolder] = useState(""); const [bank, setBank] = useState("");
  const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [platformLoading, setPlatformLoading] = useState(false); const [platformSaving, setPlatformSaving] = useState(false); const [error, setError] = useState(""); const [platformError, setPlatformError] = useState("");

  async function load() { const id = Number(tenantId); if (!Number.isInteger(id) || id <= 0) { setError("Tenant ID معتبر وارد کنید."); return; } setLoading(true); setError(""); try { const result = await api.get<SettingsData>(`/settings?tenant_id=${id}`); setData(result); setCurrency(result.settings.currency || "IRT"); setSupportUsername(result.settings.support_username || ""); setSupportUrl(result.settings.support_url || ""); setReferral(String(result.settings.referral_percent ?? 0)); setDisplayName(result.branding.display_name || ""); setPrimaryColor(result.branding.primary_color || ""); } catch (e) { setError(e instanceof Error ? e.message : "خطا در دریافت تنظیمات"); } finally { setLoading(false); } }
  async function loadPlatform() { setPlatformLoading(true); setPlatformError(""); try { const result = await api.get<PlatformData>("/settings/platform"); setPlatform(result); setFee(String(result.manual_payment.activation_fee_toman)); setCardNumber(result.manual_payment.card_number || ""); setCardHolder(result.manual_payment.card_holder || ""); setBank(result.manual_payment.bank || ""); } catch (e) { setPlatformError(e instanceof Error ? e.message : "تنظیمات مرکزی در دسترس نیست"); } finally { setPlatformLoading(false); } }
  useEffect(() => { if (tenantId) void load(); void loadPlatform(); }, []);

  async function save() { const id = Number(tenantId); const pct = Number(referral); if (!Number.isInteger(id) || id <= 0 || !Number.isFinite(pct) || pct < 0 || pct > 100) { setError("Tenant یا درصد ارجاع نامعتبر است."); return; } setSaving(true); setError(""); try { await api.put(`/settings?tenant_id=${id}`, { settings: { currency, support_username: supportUsername, support_url: supportUrl, referral_percent: pct }, branding: { display_name: displayName, primary_color: primaryColor } }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "ذخیره تنظیمات ناموفق بود"); } finally { setSaving(false); } }
  async function savePlatform() { const amount = Number(fee); if (!Number.isInteger(amount) || amount < 0) { setPlatformError("مبلغ فعال‌سازی نامعتبر است."); return; } if (amount > 0 && (!cardNumber.trim() || !cardHolder.trim())) { setPlatformError("برای مبلغ فعال، شماره کارت و نام دارنده الزامی است."); return; } setPlatformSaving(true); setPlatformError(""); try { const result = await api.put<PlatformData>("/settings/platform", { manual_payment: { activation_fee_toman: amount, card_number: cardNumber.trim(), card_holder: cardHolder.trim(), bank: bank.trim() } }); setPlatform(result); setFee(String(result.manual_payment.activation_fee_toman)); setCardNumber(result.manual_payment.card_number || ""); setCardHolder(result.manual_payment.card_holder || ""); setBank(result.manual_payment.bank || ""); } catch (e) { setPlatformError(e instanceof Error ? e.message : "ذخیره تنظیمات مرکزی ناموفق بود"); } finally { setPlatformSaving(false); } }

  return <section className="page" dir="rtl"><div className="page-header"><div><h2>تنظیمات</h2><p>تنظیمات فروشگاه، پشتیبانی، ارجاع و پیکربندی مرکزی</p></div></div>{error && <div className="card error">{error}</div>}
    {platform && <div className="card"><h3>⚙️ تنظیمات پرداخت مرکزی</h3><p>این بخش فقط برای Owner است و تنظیمات پرداخت فعال‌سازی را از داخل پنل مدیریت کنترل می‌کند؛ دیگر نیازی به تغییر Variable ریلوی برای این موارد نیست.</p>{platformError && <div className="card error">{platformError}</div>}<div className="form-grid"><label>هزینه فعال‌سازی (تومان)<input value={fee} onChange={(e) => setFee(e.target.value)} inputMode="numeric" /></label><label>شماره کارت دریافت<input value={cardNumber} onChange={(e) => setCardNumber(e.target.value)} inputMode="numeric" /></label><label>نام دارنده کارت<input value={cardHolder} onChange={(e) => setCardHolder(e.target.value)} /></label><label>بانک<input value={bank} onChange={(e) => setBank(e.target.value)} placeholder="اختیاری" /></label></div><button className="button" onClick={() => void savePlatform()} disabled={platformSaving || platformLoading}>{platformSaving ? "در حال ذخیره…" : "ذخیره تنظیمات مرکزی"}</button></div>}
    {platformError && !platform && <div className="card error">{platformError}</div>}
    <div className="card"><div className="form-grid"><label>Tenant ID<input value={tenantId} onChange={(e) => setTenantId(e.target.value)} /></label><button className="button" onClick={() => void load()} disabled={loading}>{loading ? "در حال دریافت…" : "بارگذاری"}</button></div></div>{data && <div className="card"><h3>تنظیمات Tenant</h3><div className="form-grid"><label>واحد پول<input value={currency} onChange={(e) => setCurrency(e.target.value)} /></label><label>پشتیبانی<input value={supportUsername} onChange={(e) => setSupportUsername(e.target.value)} /></label><label>لینک پشتیبانی<input value={supportUrl} onChange={(e) => setSupportUrl(e.target.value)} /></label><label>درصد ارجاع<input value={referral} onChange={(e) => setReferral(e.target.value)} inputMode="decimal" /></label><label>نام نمایشی<input value={displayName} onChange={(e) => setDisplayName(e.target.value)} /></label><label>رنگ اصلی<input value={primaryColor} onChange={(e) => setPrimaryColor(e.target.value)} placeholder="#2563eb" /></label></div><p>هزینه فعال‌سازی مرکزی: {data.activation_fee_toman.toLocaleString("fa-IR")} تومان</p><button className="button" onClick={() => void save()} disabled={saving}>{saving ? "در حال ذخیره…" : "ذخیره تغییرات"}</button></div>}</section>;
}
